version: '3.7'

services:
  mysql:
    image: examen/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
        - mynetwork
    deploy:
      replicas: 1 

  service-nodejs:
    image: examen/restapi
    ports:
      - "5050:3000"
    networks:
      - mynetwork
    deploy:
      replicas: 1 

  service-soap:
    image: examen/soapapi
    ports:
      - "4000:4000"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  service-client:
    image: examen/client
    ports:
      - "8080:80"
    networks:
      - mynetwork
    deploy:
      replicas: 4 
  
  

networks:
  mynetwork:
